#ifndef __IDMTYPES_H
#define __IDMTYPES_H

/***************************************************************************
    $Workfile:   idmtypes.h  $
    $Revision:   1.0  $
        $Date:   14 Mar 1995 10:03:12  $
      $Author:   franke  $
    Contains:      Common type definitions and defines for IDManager API.
    Last Modified: $Modtime:   12 Mar 1995 21:50:26  $

  *************************************************************************
    Copyright (C) 1995 Trilogy Development Group, Inc.
    Trilogy Development Group, Inc., Confidential and Proprietary.
    All rights reserved.  This software is subject to copyright protection 
    under the laws of the United States and other countries.
  *************************************************************************
    Comments:

***************************************************************************/

/*API return values*/
#define SB_FAILURE 0
#define SB_SUCCESS 1

/*Error Defines*/
#define SBERR_UNKNOWNPROCESSID      1200
#define SBERR_UNKNOWNCONTEXTID      1201


#endif


