#ifndef BKLOGW_H
#define BKLOGW_H

#define WND_BKLOG        0x6000
#define CNR_BKLOG        0x6222

#define ACTION_STR       "Action"
#define QTY_STR          "Quantity"
#define TYPE_STR         "Type/Model"
#define FEATURE_STR      "Feature"
#define DESC_STR         "Description"
#define CRAD_STR         "CRAD"
#define CSD_STR          "Current Scheduled Date"
#define MACH_STR         "Machine/Model"

#define BLANK            " "
#define STAR             "*"
#define FPLUS            "[+]"
#define FMINUS           "[-]"
#define FBLANK           "[ ]"
#define SLASH            "/"
#define DASH             "-"

//****************************************************************************** */
// icon ids
//****************************************************************************** */

#define ICO_4005  4005
#define ICO_4006  4006
#define ICO_4007  4007
#define ICO_4008  4008
#define ICO_4009  4009
#define ICO_4010  4010
#define ICO_4011  4011
#define ICO_4012  4012

//* F73252  New icons Ids to display how features were resolved. HECC: 07/16/2002
#define ICO_4013  4013
#define ICO_4014  4014
#define ICO_4015  4015
//* F73252  HECC: 07/16/2002

#endif
