#ifndef _EUOPIDS_H_
#define _EUOPIDS_H_

#define GENIDS                            9500
#define ID_STR_OK                         GENIDS+1
#define ID_STR_CANCEL                     GENIDS+2
#define ID_STR_HELP                       GENIDS+3
#define ID_STR_ACC_OK                     GENIDS+4
#define ID_STR_ACC_CANCEL                 GENIDS+5
#define ID_STR_ACC_HELP                   GENIDS+6
#define ID_STR_ACC_SAVE                   GENIDS+7
#define ID_STR_ACC_RESET                  GENIDS+8
#define ID_STR_ACC_DEFAULT                GENIDS+9
#define ID_STR_ACC_PRINT                  GENIDS+10
#define ID_STR_ACC_RESTORE                GENIDS+11
#define ID_STR_ACC_DELETE                 GENIDS+12
#define ID_STR_ACC_EXPORT                 GENIDS+13
#define ID_STR_ACC_EXP_SEL                GENIDS+14
#define ID_STR_ACC_COPY                   GENIDS+15
#endif
