#ifndef EUOPENU_H
#define EUOPENU_H

#define  EUOP_HLP_TABLE                       5000

#define  IDH_TBL_INITWND                      5200
#define  IDH_PNL_INITWND                      5201

#define  INITWND_PB_CANCEL                    5202
#define  INITWND_PB_HELP                      5204
#define  IDH_PNL_INITWND_PB_CANCEL            5206
#define  IDH_PNL_INITWND_PB_HELP              5208

#define  IDH_TBL_DISCWND                      5400
#define  IDH_PNL_DISCWND                      5401

#define  DISCWND_CL_BASE                      5402
#define  DISCWND_CL_MRDB                      5404
#define  DISCWND_CL_AAS                       5406
#define  DISCWND_CL_MODTYPE                   5408
#define  DISCWND_CL_DESCRIP                   5410
#define  DISCWND_CL_CRAD                      5412
#define  DISCWND_CL_INSTDT                    5414
#define  DISCWND_CL_SLNUM                     5416

#define  DISCWND_MENU_FILE                    5417
#define  DISCWND_SMENU_SAVE                   5418
#define  DISCWND_SMENU_EXIT                   5419
#define  DISCWND_SMENU_QUIT                   5420
#define  DISCWND_SMENU_PROFILE                5421

#define  DISCWND_MENU_SELECTED                5422
#define  DISCWND_SMENU_EXPLAIN                5424
#define  DISCWND_SMENU_EDIT                   5426
#define  DISCWND_SMENU_APPLY                  5428
#define  DISCWND_SMENU_IGNORE                 5430
#define  DISCWND_SMENU_EDBASE                 5432
#define  DISCWND_SMENU_EDCRAD                 5434
#define  DISCWND_SMENU_EDINSTDT               5436
#define  DISCWND_SMENU_EDSLNUM                5438

#define  DISCWND_MENU_VIEW                    5440
#define  DISCWND_SMENU_VDISC                  5442
#define  DISCWND_SMENU_VRESOL                 5444
#define  DISCWND_SMENU_VDYNLK                 5446
#define  DISCWND_SMENU_VRPOS                  5448

#define  DISCWND_PB_SAVE                      5450
#define  DISCWND_PB_EXIT                      5452
#define  DISCWND_PB_QUIT                      5454
#define  DISCWND_PB_HELP                      5456

#define  IDH_PNL_DISCWND_CL_BASE              5460
#define  IDH_PNL_DISCWND_CL_MRDB              5462
#define  IDH_PNL_DISCWND_CL_AAS               5464
#define  IDH_PNL_DISCWND_CL_MODTYPE           5466
#define  IDH_PNL_DISCWND_CL_DESCRIP           5468
#define  IDH_PNL_DISCWND_CL_CRAD              5470
#define  IDH_PNL_DISCWND_CL_INSTDT            5472
#define  IDH_PNL_DISCWND_CL_SLNUM             5474

#define  IDH_PNL_DISCWND_SMENU_SAVE           5476
#define  IDH_PNL_DISCWND_SMENU_EXIT           5477
#define  IDH_PNL_DISCWND_SMENU_QUIT           5478
#define  IDH_PNL_DISCWND_SMENU_PROFILE        5479

#define  IDH_PNL_DISCWND_MENU_FILE            5475
#define  IDH_PNL_DISCWND_MENU_SELECTED        5480
#define  IDH_PNL_DISCWND_SMENU_EXPLAIN        5482
#define  IDH_PNL_DISCWND_SMENU_EDIT           5484
#define  IDH_PNL_DISCWND_SMENU_APPLY          5486
#define  IDH_PNL_DISCWND_SMENU_IGNORE         5488
#define  IDH_PNL_DISCWND_SMENU_EDBASE         5490
#define  IDH_PNL_DISCWND_SMENU_EDCRAD         5492
#define  IDH_PNL_DISCWND_SMENU_EDINSTDT       5494
#define  IDH_PNL_DISCWND_SMENU_EDSLNUM        5496

#define  IDH_PNL_DISCWND_MENU_VIEW            5498
#define  IDH_PNL_DISCWND_SMENU_VDISC          5500
#define  IDH_PNL_DISCWND_SMENU_VRESOL         5502
#define  IDH_PNL_DISCWND_SMENU_VDYNLK         5504
#define  IDH_PNL_DISCWND_SMENU_VRPOS          5506

#define  IDH_PNL_DISCWND_PB_SAVE              5508
#define  IDH_PNL_DISCWND_PB_EXIT              5510
#define  IDH_PNL_DISCWND_PB_QUIT              5512
#define  IDH_PNL_DISCWND_PB_HELP              5514


#define  IDH_TBL_RESLWND                      5600
#define  IDH_PNL_RESLWND                      5601

#define  RESLWND_CL_BASE                      5602
#define  RESLWND_CL_MRDB                      5604
#define  RESLWND_CL_AAS                       5606
#define  RESLWND_CL_MODTYPE                   5608
#define  RESLWND_CL_DESCRIP                   5610
#define  RESLWND_CL_CRAD                      5612
#define  RESLWND_CL_INSTDT                    5614
#define  RESLWND_CL_SLNUM                     5616

#define  RESLWND_MENU_FILE                    5617
#define  RESLWND_SMENU_SAVE                   5618
#define  RESLWND_SMENU_EXIT                   5619
#define  RESLWND_SMENU_QUIT                   5620
#define  RESLWND_SMENU_PROFILE                5621

#define  RESLWND_MENU_SELECTED                5622
#define  RESLWND_SMENU_EXPLAIN                5624
#define  RESLWND_SMENU_EDIT                   5626
#define  RESLWND_SMENU_IGNORE                 5628
#define  RESLWND_SMENU_EDBASE                 5630
#define  RESLWND_SMENU_EDCRAD                 5632
#define  RESLWND_SMENU_EDINSTDT               5634
#define  RESLWND_SMENU_EDSLNUM                5636

#define  RESLWND_MENU_VIEW                    5638
#define  RESLWND_SMENU_VDISC                  5640
#define  RESLWND_SMENU_VRESOL                 5642
#define  RESLWND_SMENU_VDYNLK                 5644
#define  RESLWND_SMENU_VRPOS                  5646

#define  RESLWND_PB_SAVE                      5648
#define  RESLWND_PB_EXIT                      5650
#define  RESLWND_PB_QUIT                      5652
#define  RESLWND_PB_HELP                      5654

#define  IDH_PNL_RESLWND_CL_BASE              5656
#define  IDH_PNL_RESLWND_CL_MRDB              5658
#define  IDH_PNL_RESLWND_CL_AAS               5660
#define  IDH_PNL_RESLWND_CL_MODTYPE           5662
#define  IDH_PNL_RESLWND_CL_DESCRIP           5664
#define  IDH_PNL_RESLWND_CL_CRAD              5666
#define  IDH_PNL_RESLWND_CL_INSTDT            5668
#define  IDH_PNL_RESLWND_CL_SLNUM             5670

#define  IDH_PNL_RESLWND_MENU_FILE            5671
#define  IDH_PNL_RESLWND_SMENU_SAVE           5672
#define  IDH_PNL_RESLWND_SMENU_EXIT           5673
#define  IDH_PNL_RESLWND_SMENU_QUIT           5674
#define  IDH_PNL_RESLWND_SMENU_PROFILE        5675

#define  IDH_PNL_RESLWND_MENU_SELECTED        5676
#define  IDH_PNL_RESLWND_SMENU_EXPLAIN        5678
#define  IDH_PNL_RESLWND_SMENU_EDIT           5680
#define  IDH_PNL_RESLWND_SMENU_IGNORE         5682
#define  IDH_PNL_RESLWND_SMENU_EDBASE         5684
#define  IDH_PNL_RESLWND_SMENU_EDCRAD         5686
#define  IDH_PNL_RESLWND_SMENU_EDINSTDT       5688
#define  IDH_PNL_RESLWND_SMENU_EDSLNUM        5690

#define  IDH_PNL_RESLWND_MENU_VIEW            5692
#define  IDH_PNL_RESLWND_SMENU_VDISC          5694
#define  IDH_PNL_RESLWND_SMENU_VRESOL         5696
#define  IDH_PNL_RESLWND_SMENU_VDYNLK         5698
#define  IDH_PNL_RESLWND_SMENU_VRPOS          5700

#define  IDH_PNL_RESLWND_PB_SAVE              5702
#define  IDH_PNL_RESLWND_PB_EXIT              5704
#define  IDH_PNL_RESLWND_PB_QUIT              5706
#define  IDH_PNL_RESLWND_PB_HELP              5708


#define  IDH_TBL_GENRWND                      5800
#define  IDH_PNL_GENRWND                      5801


#define  GENRWND_PB_CANCEL                    5822
#define  GENRWND_PB_HELP                      5828


#define  IDH_PNL_GENRWND_PB_CANCEL            5850
#define  IDH_PNL_GENRWND_PB_HELP              5856

#define  IDH_TBL_XPLNWND                      6000
#define  IDH_PNL_XPLNWND                      6001


#define  IDH_PNL_XPLNWND_PB_CANCEL            6006
#define  IDH_PNL_XPLNWND_PB_HELP              6008

#define  IDH_TBL_EDTWND                       6200
#define  IDH_PNL_EDTWND                       6201


#define  IDH_PNL_EDTWND_PB_ADD                6205
#define  IDH_PNL_EDTWND_PB_CANCEL             6210
#define  IDH_PNL_EDTWND_PB_HELP               6215
#define  IDH_PNL_EDTWND_PB_SHOW_HIDE          6220
#define  IDH_PNL_EDTWND_EF_AAS                6225
#define  IDH_PNL_EDTWND_EF_BASE               6230
#define  IDH_PNL_EDTWND_EF_DATE               6235
#define  IDH_PNL_EDTWND_EF_MRDB               6240
#define  IDH_PNL_EDTWND_EF_NMBR               6245
#define  IDH_PNL_EDTWND_EF_TYPE               6250
#define  IDH_PNL_EDTWND_MLE                   6255

#define  IDH_TBL_RPOSWND                      6400
#define  IDH_PNL_RPOSWND                      6401


#define  IDH_PNL_RPOSWND_LB_RPOS              6418
#define  IDH_PNL_RPOSWND_PB_CANCEL            6420
#define  IDH_PNL_RPOSWND_PB_DELETE            6422
#define  IDH_PNL_RPOSWND_PB_HELP              6424
#define  IDH_PNL_RPOSWND_PB_SAVE              6426
#define  IDH_PNL_RPOSWND_POP_DELETE           6428
#define  IDH_PNL_RPOSWND_POP_SAVE             6430
#define  IDH_PNL_RPOSWND_POP_RESTORE          6432
#define  IDH_PNL_RPOSWND_POP_SORT             6434
#define  IDH_PNL_RPOSWND_POP_SORT_UP          6436
#define  IDH_PNL_RPOSWND_POP_SORT_DOWN        6438

#define  IDH_TBL_PROFWND                      6600
#define  IDH_PNL_PROFWND                      6601


#define  IDH_PNL_PROFWND_RB_DISPOPT           6656
#define  IDH_PNL_PROFWND_RB_DISP_ALL          6658
#define  IDH_PNL_PROFWND_RB_DISP_DISC         6660

#define  IDH_PNL_PROFWND_RB_PROCOPT           6662
#define  IDH_PNL_PROFWND_RB_PROC_GRPOS        6664
#define  IDH_PNL_PROFWND_RB_PROC_GRPOSY       6666
#define  IDH_PNL_PROFWND_RB_PROC_GRPOSYL      6668
#define  IDH_PNL_PROFWND_RB_PROC_GRPOSYA      6670
#define  IDH_PNL_PROFWND_RB_PROC_GRPOSN       6672
#define  IDH_PNL_PROFWND_RB_PROC_APPLY        6674
#define  IDH_PNL_PROFWND_RB_PROC_APPLYY       6676
#define  IDH_PNL_PROFWND_RB_PROC_APPLYN       6678
#define  IDH_PNL_PROFWND_RB_PROC_DISPAE       6680
#define  IDH_PNL_PROFWND_RB_PROC_DISPAEY      6682
#define  IDH_PNL_PROFWND_RB_PROC_DISPAEN      6684

#define  IDH_PNL_PROFWND_CB_VIEWOPT           6686
#define  IDH_PNL_PROFWND_CB_VIEW_DISC         6688
#define  IDH_PNL_PROFWND_CB_VIEW_PROF         6690
#define  IDH_PNL_PROFWND_CB_VIEW_EDT          6692
#define  IDH_PNL_PROFWND_CB_VIEW_RESOL        6694
#define  IDH_PNL_PROFWND_CB_VIEW_GRPO         6696
#define  IDH_PNL_PROFWND_CB_VIEW_DYNIL        6698

#define  IDH_PNL_PROFWND_PB_APPLY             6700
#define  IDH_PNL_PROFWND_PB_DEFAULT           6702
#define  IDH_PNL_PROFWND_PB_RESET             6704
#define  IDH_PNL_PROFWND_PB_CANCEL            6706
#define  IDH_PNL_PROFWND_PB_HELP              6708

#endif
