#define WND_MAIN                       3333
#define WND_MAIN_MCC                   WND_MAIN+1
#define TIMER_TXT                      WND_MAIN+2
#define TIMER_CTL                      WND_MAIN+3

#define WND_MAIN_VP                    WND_MAIN+4
#define WND_MAIN_MCCE                  WND_MAIN+5
#define WND_MAIN_TEXT                  WND_MAIN+6
#define WND_MAIN_LABEL1                WND_MAIN+7
#define WND_MAIN_LABEL2                WND_MAIN+8
#define WND_MAIN_LABEL3                WND_MAIN+9
#define WND_MAIN_LABEL4                WND_MAIN+10
#define WND_MAIN_LABEL5                WND_MAIN+11
#define WND_MAIN_TEXT1                 WND_MAIN+12
#define WND_MAIN_TEXT2                 WND_MAIN+13
#define WND_MAIN_TEXT3                 WND_MAIN+14
#define WND_MAIN_TEXT4                 WND_MAIN+15
#define WND_MAIN_TEXT5                 WND_MAIN+16
#define WND_MAIN_PB_HIDE               WND_MAIN+17
#define WND_MAIN_TIMER_CTL             WND_MAIN+18
#define WND_MAIN_PB_RESOLVE            WND_MAIN+19
#define WND_MAIN_PB_REBUILD            WND_MAIN+20
#define WND_MAIN_PB_WRITE              WND_MAIN+21
#define WND_MAIN_PB_SAVE               WND_MAIN+22
#define WND_MAIN_MI_FILE               WND_MAIN+23
#define WND_MAIN_MI_HELP               WND_MAIN+24
#define WND_MAIN_MI_ABOUT              WND_MAIN+25
#define WND_MAIN_MI_T                  WND_MAIN+100
#define WND_MAIN_MI_T_SD               WND_MAIN+101
#define WND_MAIN_MI_T_RPOL             WND_MAIN+102
#define WND_MAIN_MI_T_XPLNL            WND_MAIN+103
#define WND_MAIN_MI_T_FL               WND_MAIN+104
#define WND_MAIN_MI_T_SML              WND_MAIN+105
#define WND_MAIN_MI_T_MRL              WND_MAIN+106
#define WND_MAIN_MI_T_ML               WND_MAIN+107
#define WND_MAIN_MI_T_BLL              WND_MAIN+108
#define WND_MAIN_MI_T_PRT              WND_MAIN+109
#define WND_MAIN_MI_T_STUB_RESOLVED    WND_MAIN+110
#define WND_MAIN_MI_T_UPL              WND_MAIN+111
#define WND_MAIN_MI_T_PK               WND_MAIN+112
#define WND_MAIN_MI_T_MMW              WND_MAIN+113
#define WND_MAIN_MI_T_L10              WND_MAIN+114
#define WND_MAIN_ID_RESOLVE            WND_MAIN+115      //edw 03-20-97

#define WND_MAIN_MI_PKFILE             WND_MAIN+33
#define WND_MAIN_MI_BLW                WND_MAIN+34
#define WND_MAIN_MI_VIEW               WND_MAIN+35
#define WND_MAIN_MI_DISCW              WND_MAIN+36
#define WND_MAIN_MI_RESW               WND_MAIN+37
#define WND_MAIN_MI_RPOW               WND_MAIN+38
#define WND_MAIN_MI_PRINT              WND_MAIN+39
#define WND_MAIN_MI_NEW                WND_MAIN+41
#define WND_MAIN_MI_OPEN               WND_MAIN+42
#define WND_MAIN_MI_SAVE               WND_MAIN+43
#define WND_MAIN_MI_SAVEAS             WND_MAIN+44
#define WND_MAIN_MI_GENCFR             WND_MAIN+45
#define WND_MAIN_MI_PROFILE            WND_MAIN+46
#define WND_MAIN_MI_SW                 WND_MAIN+47
#define WND_MAIN_MI_EXIT               WND_MAIN+48
#define WND_MAIN_MI_PPRVW              WND_MAIN+49

#define MAINWND_STR_ERR                WND_MAIN+50
#define MAINWND_STR_LABEL1             WND_MAIN+51
#define MAINWND_STR_LABEL2             WND_MAIN+52
#define MAINWND_STR_LABEL3             WND_MAIN+53
#define MAINWND_STR_LABEL4             WND_MAIN+54
#define MAINWND_STR_LABEL5             WND_MAIN+55
#define MAINWND_STR_UNC                WND_MAIN+56
#define MAINWND_STR_IUO                WND_MAIN+57
#define MAINWND_STR_CONF               WND_MAIN+58
#define MAINWND_STR_DISC               WND_MAIN+59
#define MAINWND_STR_RESO               WND_MAIN+60
#define MAINWND_STR_GET_CFR_NAME_TITLE WND_MAIN+61
#define MAINWND_STR_R_U_SURE           WND_MAIN+62
#define MAINWND_STR_HELPTITLE          WND_MAIN+63
#define MAINWND_STR_RM2                WND_MAIN+64

#define WND_MAIN_MI_T_PPRVW            WND_MAIN+65

#define MAINW_MSG_SPOOLING_JOB         WND_MAIN+66
#define MAINW_MSG_SPOOL_JOB            WND_MAIN+67
#define MAINW_MSG_WRITING              WND_MAIN+68
#define MAINW_MSG_SAVING               WND_MAIN+69
#define MAINW_MSG_REBUILDING           WND_MAIN+70
#define MAINW_MSG_READING_AAS          WND_MAIN+71
#define MAINW_MSG_READING_MRDB         WND_MAIN+72
#define MAINW_MSG_BLDG_PK              WND_MAIN+73
#define MAINW_MSG_RESOLVING            WND_MAIN+74
#define MAINWND_STR_ALREADY_STARTED    WND_MAIN+75
#define MAINWND_STR_GET_AAS_NAME_TITLE WND_MAIN+76
#define MAINWND_STR_GET_SAVED_NAME_TITLE WND_MAIN+77
#define MAINWND_STR_GET_SAVE_NAME_TITLE WND_MAIN+78
#define MAINW_MSG_SPOOL_ERR            WND_MAIN+79
#define MAINWND_STR_SET_PKFILE_TITLE   WND_MAIN+80
#define MAINW_MSG_ERR_NO_FILE          WND_MAIN+81
#define MAINW_MSG_ERR_NO_PKFILE        WND_MAIN+82
#define MAINW_MSG_ERR_DMGD_PKFILE      WND_MAIN+83
#define MAINW_MSG_ERR_NO_PKFILE_IN_DIR WND_MAIN+84
#define MAINW_MSG_NOTRESOLVED          WND_MAIN+85
#define MAINW_MSG_NOTRESOLVED_TITLE    WND_MAIN+86

#define BL_STR_MACH_HW_1               WND_MAIN+200
#define BL_STR_MACH_HW_2               WND_MAIN+201
#define BL_STR_MACH_HW_3               WND_MAIN+202
#define BL_STR_MACH_HW_4               WND_MAIN+203
#define BL_STR_MACH_HW_5               WND_MAIN+204
#define BL_STR_MACH_HW_6               WND_MAIN+205
#define BL_STR_MACH_HW_A               WND_MAIN+206
#define BL_STR_MACH_HW_B               WND_MAIN+207
#define BL_STR_MACH_HW_C               WND_MAIN+208
#define BL_STR_MACH_SW_1               WND_MAIN+209
#define BL_STR_MACH_SW_2               WND_MAIN+210
#define BL_STR_MACH_SW_3               WND_MAIN+211
#define BL_STR_MACH_SW_4               WND_MAIN+212
#define BL_STR_MACH_SW_5               WND_MAIN+213
#define BL_STR_MACH_SW_A               WND_MAIN+214
#define BL_STR_MACH_SW_B               WND_MAIN+215
#define BL_STR_MACH_SW_C               WND_MAIN+216
#define BL_STR_FEAT_HW_1               WND_MAIN+217
#define BL_STR_FEAT_HW_2               WND_MAIN+218
#define BL_STR_FEAT_HW_3               WND_MAIN+219
#define BL_STR_FEAT_HW_4               WND_MAIN+220
#define BL_STR_FEAT_HW_6               WND_MAIN+221
#define BL_STR_FEAT_HW_7               WND_MAIN+222
#define BL_STR_FEAT_HW_8               WND_MAIN+223
#define BL_STR_FEAT_SW_1               WND_MAIN+224
#define BL_STR_FEAT_SW_2               WND_MAIN+225
#define BL_STR_FEAT_SW_3               WND_MAIN+226
#define BL_STR_FEAT_SW_4               WND_MAIN+227
#define BL_STR_FEAT_SW_5               WND_MAIN+228
#define BL_STR_FEAT_SW_A               WND_MAIN+229
#define BL_STR_FEAT_SW_B               WND_MAIN+230

//#define DLG_ABOUT                      4544
//#define DLG_ABOUT_ICON                 4545
//#define DLG_ABOUT_T1                   4546
//#define DLG_ABOUT_T2                   4547
//#define DLG_ABOUT_T3                   4548
//#define DLG_ABOUT_GP                   4549
//#define DLG_ABOUT_IGP                  4550

#define DLG_UPLOAD_RPO_TITLE           4560
#define DLG_UPLOAD_RPO_TEXT            4561
#define DLG_UPLOAD_CFREPORT_TITLE      4562
#define DLG_UPLOAD_CFREPORT_TEXT       4563
#define ERROR_HLLAPI_ERR               4564
#define ERROR_UPLOAD_RPO_HLLAPI_ERR    4565
#define ERROR_UPLOAD_CFR_HLLAPI_ERR    4566
#define ERROR_RPO_FILE_ERROR           4567

#define ID_DLG_PKFILE                  4580
#define ID_DLG_PKFILE_PK_DFLT          4581
//edw1/7/98 #define STR_AssetManage                "PWSPROGA AT "HQVMIC1"
#define STR_ApplyLocale                "EN_US"
#define STR_EndReconciliation          "Data resolved. Select 'File' | 'End reconciliation' to continue"

//edw1/14/97 - strings for new UBOHOST commands
#define STR_TagRename                  "RENAME"
#define STR_TagExecute                 "EXECUTE"
#define STR_ExtToExec                  "EXT EXEC A"
#define STR_RPOExecCommand             "NBHWMES"

#define STR_CFRLockIndicator           "05 BaseRetrieval - S390 Non-orderable flag"
