#ifndef MMW2_H
#define MMW2_H


#define MMWND_ICON_DUMMY        0x4111
#define WND_MM                  0x7300

#define MMWND_MLE                                   WND_MM+1
#define MMWND_PB_HELP                               WND_MM+2
#define MMWND_RB_1                                  WND_MM+3
#define MMWND_RB_2                                  WND_MM+4
#define MMWND_SCV_PBS                               WND_MM+5
#define MMWND_STR_HELPTITLE                         WND_MM+6
#define MMWND_STR_PB_HELP                           WND_MM+7
//#define MMWND_STR_PB_OK                             WND_MM+8
//#define MMWND_STR_PB_CANCEL                         WND_MM+9
#define MMWND_VPORT                                 WND_MM+10
#define MMWND_MCC                                   WND_MM+11
#define MMWND_ICON                                  WND_MM+12
#define MMWND_TEXT_PPAC1                            WND_MM+13 //53915 MAMT 28/02/2001
#define MMWND_TEXT_PPAC2                            WND_MM+14 //53915 MAMT 28/02/2001
#define MMWND_TEXT_PPAC3                            WND_MM+15 //53915 MAMT 28/02/2001
#define MMWND_TEXT_PPAC4                            WND_MM+16 //53915 MAMT 28/02/2001

#endif








