#define WND_PPRVW                      4600
#define PPRVW_POPUP                    4601
#define  PPRFW_ID_GB                   WND_PPRVW+10
#define  PPRFW_ID_MLE                  WND_PPRVW+11
#define  PPRFW_ID_MLE_CNTL             WND_PPRVW+12
#define  PPRVW_ID_POP_COPY             WND_PPRVW+13
#define  PPRVW_ID_POP_PRINT            WND_PPRVW+14
#define  PPRVW_ID_POP_HELP             WND_PPRVW+15
#define  PPRVW_ID_POP_EXPORT           WND_PPRVW+16
#define  PPRVW_ID_POP_EXPORT_SEL       WND_PPRVW+17
#define  PPRVW_ID_POP_CANCEL           WND_PPRVW+18
#define  PPRVW_ID_PB_HELP              WND_PPRVW+19
#define  PPRVW_ID_MCCE                 WND_PPRVW+20
#define  PPRVW_ID_TEXT_TIMER           WND_PPRVW+21
#define  PPRVW_ID_TIMER                WND_PPRVW+22

