#ifndef _AB_PRFL_H_
#define _AB_PRFL_H_

#define PRFL                                   0x7700
#define PRFL_STR_MNTH_JAN                      PRFL+1
#define PRFL_STR_MNTH_FEB                      PRFL+2
#define PRFL_STR_MNTH_MAR                      PRFL+3
#define PRFL_STR_MNTH_APR                      PRFL+4
#define PRFL_STR_MNTH_MAY                      PRFL+5
#define PRFL_STR_MNTH_JUN                      PRFL+6
#define PRFL_STR_MNTH_JUL                      PRFL+7
#define PRFL_STR_MNTH_AUG                      PRFL+8
#define PRFL_STR_MNTH_SEP                      PRFL+9
#define PRFL_STR_MNTH_OCT                      PRFL+10
#define PRFL_STR_MNTH_NOV                      PRFL+11
#define PRFL_STR_MNTH_DEC                      PRFL+12

#endif
