#ifndef PRFW4_H
#define PRFW4_H


#define WND_PRF                  0x7000

#define PRFLWNDW_MCCCONTROL                         WND_PRF+1
#define PRFLWND_CB_GENRPO                           WND_PRF+2
#define PRFLWND_GB_DSPLY                            WND_PRF+3
#define PRFLWND_GB_WORKDIR                          WND_PRF+4
//#define PRFLWND_PB_SAVE                             WND_PRF+5
//#define PRFLWND_PB_CANCEL                           WND_PRF+6
#define PRFLWND_PB_DEFAULT                          WND_PRF+7
#define PRFLWND_PB_HELP                             WND_PRF+8
#define PRFLWND_PB_RESET                            WND_PRF+9
#define PRFLWND_RB_DSPLYALL                         WND_PRF+10
#define PRFLWND_RB_DSPLYDSCRP                       WND_PRF+11
#define PRFLWND_SCV_PBS                             WND_PRF+12
#define PRFLWND_STR_CB_GENRPO                       WND_PRF+13
#define PRFLWND_STR_ERR_BAD_WORKDIR                 WND_PRF+14
#define PRFLWND_STR_ERR_NO_WORKDIR                  WND_PRF+15
#define PRFLWND_STR_ERR_TITLE                       WND_PRF+16
#define PRFLWND_STR_GB_DSPLY                        WND_PRF+17
#define PRFLWND_STR_GB_WORKDIR                      WND_PRF+18
#define PRFLWND_STR_HELPTITLE                       WND_PRF+19
#define PRFLWND_STR_PB_APPLY                        WND_PRF+20
#define PRFLWND_STR_PB_CANCEL                       WND_PRF+21
#define PRFLWND_STR_PB_DEFAULT                      WND_PRF+22
#define PRFLWND_STR_PB_HELP                         WND_PRF+23
#define PRFLWND_STR_PB_RESET                        WND_PRF+24
#define PRFLWND_STR_RB_DSPLYALL                     WND_PRF+25
#define PRFLWND_STR_RB_DSPLYDSCRP                   WND_PRF+26
#define PRLWND_EF_WORKDIR                           WND_PRF+27
#endif
