#ifndef _AB_RPOW_H_
#define _AB_RPOW_H_

#define WND_RPO                             0x5000

#define RPOSWND_POPUP                       0x5050
#define RPOSWND_HLP_TABLE                   0x5060

#define RPOSWND_GB                          WND_RPO+1
#define RPOSWND_CNR_RPOS                    WND_RPO+3
#define RPOSWND_LB_RPOSH                    WND_RPO+5
#define RPOSWND_MCC                         WND_RPO+4
//#define RPOSWND_PB_CANCEL                   WND_RPO+5
#define RPOSWND_PB_DELETE                   WND_RPO+6
#define RPOSWND_PB_HELP                     WND_RPO+7
//#define RPOSWND_PB_SAVE                     WND_RPO+8
#define RPOSWND_PB_SCV                      WND_RPO+9
#define RPOSWND_POP_DELETE                  WND_RPO+10
#define RPOSWND_POP_SAVE                    WND_RPO+11
#define RPOSWND_POP_RESTORE                 WND_RPO+12
//#define RPOSWND_STR_CANCEL                  WND_RPO+13
#define RPOSWND_STR_DELETE                  WND_RPO+14
#define RPOSWND_STR_RESTORE                 WND_RPO+15
#define RPOSWND_STR_GB_RPOS                 WND_RPO+16
//#define RPOSWND_STR_HELP                    WND_RPO+17
#define RPOSWND_STR_HELPTITLE               WND_RPO+18
#define RPOSWND_STR_INFO_CANCEL             WND_RPO+19
#define RPOSWND_STR_INFO_DELETE             WND_RPO+20
#define RPOSWND_STR_INFO_RESTORE            WND_RPO+21
#define RPOSWND_STR_INFO_HELP               WND_RPO+22
#define RPOSWND_STR_INFO_INACT              WND_RPO+23
#define RPOSWND_STR_INFO_SAVE               WND_RPO+24
//#define RPOSWND_STR_SAVE                    WND_RPO+25
#define RPOSWND_VP_CLIENT                   WND_RPO+26

#define RPOSWND_POP_SORT                    WND_RPO+26
#define RPOSWND_POP_SORT_UP                 WND_RPO+27
#define RPOSWND_POP_SORT_DOWN               WND_RPO+28
#define RPOSWND_STR_SORT                    WND_RPO+29
#define RPOSWND_STR_SORT_UP                 WND_RPO+30
#define RPOSWND_STR_SORT_DOWN               WND_RPO+31
#define RPOSWND_STR_INFO_SORT               WND_RPO+32
#define RPOSWND_STR_INFO_SORT_UP            WND_RPO+33
#define RPOSWND_STR_INFO_SORT_DOWN          WND_RPO+34
#define RPOSWND_STR_COL_NUMBER              WND_RPO+35
#define RPOSWND_STR_COL_ACTION              WND_RPO+36
#define RPOSWND_STR_COL_MMF                 WND_RPO+37
#define RPOSWND_STR_COL_DESC                WND_RPO+38


#define RPOSWND_TEST_THRD_SYS              WND_RPO+50
#define RPOSWND_TEST_THRD_OPTLINK          WND_RPO+51
#define RPOSWND_TEST_THRD_MEMBER           WND_RPO+52

#define RPOSWND_PB_SUBMIT                  WND_RPO+53   //* 73686 HECC: 08/28/2002
#define RPOSWND_STR_SUBMIT                 WND_RPO+54   //* 73686 HECC: 08/28/2002

#endif



