#ifndef _RPOINFO_H_
#define _RPOINFO_H_

#define DID_OK                IDC_PB_OK
#define DID_CANCEL            IDC_PB_Cancel

/* Control Ids */
#define DLG_RPOINFOPNL                         10200
#define ID_GRP_USER_INFORMATION                10201
#define ID_TXT_USER_NAME                       10202
#define ID_ENTRY_USER_NAME                     10204
#define ID_TXT_TIE_LINE                        10205
#define ID_ENTRY_TIE_LINE                      10208
#define ID_TXT_VM_USER_ID                      10209
#define ID_ENTRY_VM_USER_ID                    10210
#define ID_TXT_VM_NODE_ID                      10211
#define ID_ENTRY_VM_NODE_ID                    10212
#define ID_GRP_FEDERAL_CUSTOMER                10213
#define ID_RADIO_FEDCUST_YES                   10214
#define ID_RADIO_FEDCUST_NO                    10215
#define ID_TXT_SPECIAL_CONTRACT_NUMBER         10216
#define ID_TXT_SPECIAL_CONTRACT_NUMBER_2       10217
#define ID_ENTRY_SPECIAL_CONTRACT_NUMBER       10218
#define ID_GRP_EDUCATIONAL_ALLOWANCE_APPLIES   10219
#define ID_RADIO_EDALLOW_YES                   10220
#define ID_RADIO_EDALLOW_NO                    10221
#define ID_GRP_CUSTOMER_STATUS                 10222
#define ID_RADIO_CUSTSTATUS_OWNING             10223
#define ID_RADIO_CUSTSTATUS_USING              10224
#define ID_GRP_MACHINE_STATUS                  10225
#define ID_RADIO_MACSTATUS_LEASE               10226
#define ID_RADIO_MACSTATUS_PURCHASEMAINTENANCE 10227
#define ID_RADIO_MACSTATUS_PURCHASEPER_CALL    10228
#define ID_PUSH_HELP                           10229

/* String ids */
#define TXT_USER_INFORMATION                   10301
#define TXT_USER_NAME                          10302
#define TXT_TIE_LINE                           10303
#define TXT_VM_USER_ID                         10304
#define TXT_VM_NODE_ID                         10305
#define TXT_FEDERAL_CUSTOMER                   10306
#define TXT_YES                                10307
#define TXT_NO                                 10308
#define TXT_SPECIAL_CONTRACT_NUMBER            10309
#define TXT_SPECIAL_CONTRACT_NUMBER_2          10310
#define TXT_EDUCATIONAL_ALLOWANCE_APPLIES      10311
#define TXT_CUSTOMER_STATUS                    10312
#define TXT_OWNING                             10313
#define TXT_USING                              10314
#define TXT_MACHINE_STATUS                     10315
#define TXT_LEASE                              10316
#define TXT_PURCHASEMAINTENANCE                10317
#define TXT_PURCHASEPER_CALL                   10318
#define TXT_OK                                 10319
#define TXT_CANCEL                             10320
#define TXT_HELP                               10321

#endif
