#ifndef _AB_SWDW_H_
#define _AB_SWDW_H_

#define WND_SWD                             0x5500

#define SWDW_ID_POPUP                       0x5550
#define SWDW_ID_HLP_TABLE                   0x5560

#define SWDW_ID_GB                          WND_SWD+1
#define SWDW_ID_CNR                         WND_SWD+2
#define SWDW_ID_MCC                         WND_SWD+3
#define SWDW_ID_POP_SORT                    WND_SWD+4
#define SWDW_ID_POP_SORT_TYPE               WND_SWD+5
#define SWDW_ID_POP_SORT_MODEL              WND_SWD+6
#define SWDW_ID_POP_SORT_FEAT               WND_SWD+7
#define SWDW_ID_POP_SORT_DESC               WND_SWD+8
#define SWDW_ID_POP_HELP                    WND_SWD+9
#define SWDW_ID_POP_CANCEL                  WND_SWD+10
#define SWDW_ID_STR_COL_TYPE                WND_SWD+11
#define SWDW_ID_STR_COL_MODEL               WND_SWD+12
#define SWDW_ID_STR_COL_FEAT                WND_SWD+13
#define SWDW_ID_STR_COL_DESC                WND_SWD+14
#define SWDW_ID_STR_HELPTITLE               WND_SWD+15
#define SWDW_ID_SC                          WND_SWD+16
#define SWDW_ID_PB_HELP                     WND_SWD+17

#endif
