#ifndef _AB_XPLNW_H_
#define _AB_XPLNW_H_

#define   WND_XPLN                          0x7500

#define XPLNWND_HLP_TABLE                   0x7520

#define XPLNWND_PB_CANCEL                   WND_XPLN+1
#define XPLNWND_PB_HELP                     WND_XPLN+2
#define XPLNWND_PB_SCV                      WND_XPLN+3
#define XPLNWND_STR_CANCEL                  WND_XPLN+4
#define XPLNWND_STR_HELP                    WND_XPLN+5
#define XPLNWND_STR_HELPTITLE               WND_XPLN+6
#define XPLNWND_XPLNCNTL                    WND_XPLN+7
#define XPLNWND_UM_SETFOCUS                 WND_XPLN+8
#endif
