#ifdef INCL_I0STRING
#include <I0STRING.HPP>
#endif
#ifdef INCL_I3STATECHECKBOX
#include <I3STATBX.HPP>
#endif
#ifdef INCL_IACCELERATOR
#include <IACCEL.HPP>
#endif
#ifdef INCL_IAPPLICATION
#include <IAPP.HPP>
#endif
#ifdef INCL_ICURRENTAPPLICATION
#include <IAPP.HPP>
#endif
#ifdef INCL_IBASE
#include <IBASE.HPP>
#endif
#ifdef INCL_IBITFLAG
#include <IBITFLAG.HPP>
#endif
#ifdef INCL_IBITMAPCONTROL
#include <IBMPCTL.HPP>
#endif
#ifdef INCL_IBUFFER
#include <IBUFFER.HPP>
#endif
#ifdef INCL_IBUTTON
#include <IBUTTON.HPP>
#endif
#ifdef INCL_ICANVAS
#include <ICANVAS.HPP>
#endif
#ifdef INCL_ICHECKBOX
#include <ICHECKBX.HPP>
#endif
#ifdef INCL_ICOMMANDEVENT
#include <ICMDEVT.HPP>
#endif
#ifdef INCL_ICOMMANDHANDLER
#include <ICMDHDR.HPP>
#endif
#ifdef INCL_ICNRCONTROLLIST
#include <ICNRCLST.HPP>
#endif
#ifdef INCL_ICONTAINERCOLUMN
#include <ICNRCOL.HPP>
#endif
#ifdef INCL_ICONTAINERCONTROL
#include <ICNRCTL.HPP>
#endif
#ifdef INCL_ICNRDRAWITEMEVENT
#include <ICNRDIEV.HPP>
#endif
#ifdef INCL_ICNRDRAWBACKGROUNDEVENT
#include <ICNRDIEV.HPP>
#endif
#ifdef INCL_ICNRDRAWHANDLER
#include <ICNRDIHD.HPP>
#endif
#ifdef INCL_ICNREDITEVENT
#include <ICNREEVT.HPP>
#endif
#ifdef INCL_ICNRREALLOCSTRINGEVENT
#include <ICNREEVT.HPP>
#endif
#ifdef INCL_ICNRBEGINEDITEVENT
#include <ICNREEVT.HPP>
#endif
#ifdef INCL_ICNRENDEDITEVENT
#include <ICNREEVT.HPP>
#endif
#ifdef INCL_ICNREDITHANDLER
#include <ICNREHDR.HPP>
#endif
#ifdef INCL_ICNREVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNRENTEREVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNREMPHASISEVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNRQUERYDELTAEVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNRSCROLLEVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNRHELPEVENT
#include <ICNREVT.HPP>
#endif
#ifdef INCL_ICNRHANDLER
#include <ICNRHDR.HPP>
#endif
#ifdef INCL_ICNRMENUHANDLER
#include <ICNRMHDR.HPP>
#endif
#ifdef INCL_ICONTAINEROBJECT
#include <ICNROBJ.HPP>
#endif
#ifdef INCL_ICNROBJECTSET
#include <ICNROLST.HPP>
#endif
#ifdef INCL_ICOLOR
#include <ICOLOR.HPP>
#endif
#ifdef INCL_IDEVICECOLOR
#include <ICOLOR.HPP>
#endif
#ifdef INCL_IGUICOLOR
#include <ICOLOR.HPP>
#endif
#ifdef INCL_ICOMBOBOX
#include <ICOMBOBX.HPP>
#endif
#ifdef INCL_ICONTROL
#include <ICONTROL.HPP>
#endif
#ifdef INCL_ICRITSEC
#include <ICRITSEC.HPP>
#endif
#ifdef INCL_ICONTROLEVENT
#include <ICTLEVT.HPP>
#endif
#ifdef INCL_IDATE
#include <IDATE.HPP>
#endif
#ifdef INCL_IDBCSBUFFER
#include <IDBCSBUF.HPP>
#endif
#ifdef INCL_IDDECLIENTCONVERSATION
#include <IDDECCNV.HPP>
#endif
#ifdef INCL_IDDEACTIVESERVER
#include <IDDECSET.HPP>
#endif
#ifdef INCL_IDDEACTIVESERVERSET
#include <IDDECSET.HPP>
#endif
#ifdef INCL_IDDECLIENTHOTLINKSET
#include <IDDECSET.HPP>
#endif
#ifdef INCL_IDDEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEACKNOWLEDGEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDESETACKNOWLEDGEINFOEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDECLIENTACKNOWLEDGEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDESERVERACKNOWLEDGEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEACKNOWLEDGEPOKEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEACKNOWLEDGEEXECUTEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEDATAEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDECLIENTHOTLINKEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEREQUESTDATAEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEPOKEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEEXECUTEEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDESERVERHOTLINKEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEENDEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDECLIENTENDEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDEBEGINEVENT
#include <IDDEEVT.HPP>
#endif
#ifdef INCL_IDDETOPICSERVER
#include <IDDETSRV.HPP>
#endif
#ifdef INCL_IDRAWITEMEVENT
#include <IDIEVT.HPP>
#endif
#ifdef INCL_IDMCNRITEM
#include <IDMCNRIT.HPP>
#endif
#ifdef INCL_IDMEFITEM
#include <IDMEFIT.HPP>
#endif
#ifdef INCL_IDMEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCEBEGINEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCERENDEREVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCEPREPAREEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCEENDEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCEDISCARDEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMSOURCEPRINTEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMTARGETENTEREVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMTARGETLEAVEEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMTARGETDROPEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMTARGETHELPEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMTARGETENDEVENT
#include <IDMEVENT.HPP>
#endif
#ifdef INCL_IDMHANDLER
#include <IDMHNDLR.HPP>
#endif
#ifdef INCL_IDMIMAGE
#include <IDMIMAGE.HPP>
#endif
#ifdef INCL_IDMITEM
#include <IDMITEM.HPP>
#endif
#ifdef INCL_IDMMLEITEM
#include <IDMMLEIT.HPP>
#endif
#ifdef INCL_IDMOPERATION
#include <IDMOPER.HPP>
#endif
#ifdef INCL_IDMITEMPROVIDER
#include <IDMPROV.HPP>
#endif
#ifdef INCL_IDMITEMPROVIDERFOR
#include <IDMPROV.HPP>
#endif
#ifdef INCL_IDMRENDERER
#include <IDMRENDR.HPP>
#endif
#ifdef INCL_IDMSOURCEHANDLER
#include <IDMSRCH.HPP>
#endif
#ifdef INCL_IDMSOURCEOPERATION
#include <IDMSRCOP.HPP>
#endif
#ifdef INCL_IDMSOURCERENDERER
#include <IDMSRCRN.HPP>
#endif
#ifdef INCL_IDMTARGETHANDLER
#include <IDMTGTH.HPP>
#endif
#ifdef INCL_IDMTARGETOPERATION
#include <IDMTGTOP.HPP>
#endif
#ifdef INCL_IDMTARGETRENDERER
#include <IDMTGTRN.HPP>
#endif
#ifdef INCL_IEDITHANDLER
#include <IEDITHDR.HPP>
#endif
#ifdef INCL_IENTRYFIELD
#include <IENTRYFD.HPP>
#endif
#ifdef INCL_IEVENT
#include <IEVENT.HPP>
#endif
#ifdef INCL_IEVENTDATA
#include <IEVTDATA.HPP>
#endif
#ifdef INCL_IEXCEPTIONLOCATION
#include <IEXCBASE.HPP>
#endif
#ifdef INCL_IEXCEPTION
#include <IEXCBASE.HPP>
#endif
#ifdef INCL_IERRORINFO
#include <IEXCEPT.HPP>
#endif
#ifdef INCL_IGUIERRORINFO
#include <IEXCEPT.HPP>
#endif
#ifdef INCL_ISYSTEMERRORINFO
#include <IEXCEPT.HPP>
#endif
#ifdef INCL_IFILEDIALOG
#include <IFILEDLG.HPP>
#endif
#ifdef INCL_IFILEDIALOGEVENT
#include <IFILEHDR.HPP>
#endif
#ifdef INCL_IFILEDIALOGHANDLER
#include <IFILEHDR.HPP>
#endif
#ifdef INCL_IFOCUSHANDLER
#include <IFOCSHDR.HPP>
#endif
#ifdef INCL_IFONT
#include <IFONT.HPP>
#endif
#ifdef INCL_IFONTDIALOG
#include <IFONTDLG.HPP>
#endif
#ifdef INCL_IFONTDIALOGHANDLER
#include <IFONTHDR.HPP>
#endif
#ifdef INCL_IFRAMEWINDOW
#include <IFRAME.HPP>
#endif
#ifdef INCL_IFRAMEEVENT
#include <IFRAMEVT.HPP>
#endif
#ifdef INCL_IFRAMEFORMATEVENT
#include <IFRAMEVT.HPP>
#endif
#ifdef INCL_IFRAMEEXTENSION
#include <IFRAMEXT.HPP>
#endif
#ifdef INCL_IFRAMEEXTENSIONS
#include <IFRAMEXT.HPP>
#endif
#ifdef INCL_IFRAMEHANDLER
#include <IFRAMHDR.HPP>
#endif
#ifdef INCL_IGRAPHICPUSHBUTTON
#include <IGRAPHBT.HPP>
#endif
#ifdef INCL_IGROUPBOX
#include <IGROUPBX.HPP>
#endif
#ifdef INCL_IHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IWINDOWHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IANCHORBLOCKHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IMODULEHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IPOINTERHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_ISYSTEMPOINTERHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_ISTRINGHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_ISEMAPHOREHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IPRESSPACEHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IBITMAPHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_ISYSTEMBITMAPHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IPROFILEHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IMESSAGEQUEUEHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IACCELTBLHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_ITHREADID
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IPROCESSID
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IENUMHANDLE
#include <IHANDLE.HPP>
#endif
#ifdef INCL_IHANDLER
#include <IHANDLER.HPP>
#endif
#ifdef INCL_IHELPWINDOW
#include <IHELP.HPP>
#endif
#ifdef INCL_IHELPMENUBAREVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPERROREVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPHYPERTEXTEVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPSUBITEMNOTFOUNDEVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPTUTORIALEVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPNOTIFYEVENT
#include <IHELPEVT.HPP>
#endif
#ifdef INCL_IHELPHANDLER
#include <IHELPHDR.HPP>
#endif
#ifdef INCL_IICONCONTROL
#include <IICONCTL.HPP>
#endif
#ifdef INCL_IINFOAREA
#include <IINFOA.HPP>
#endif
#ifdef INCL_IKEYBOARDEVENT
#include <IKEYEVT.HPP>
#endif
#ifdef INCL_IKEYBOARDHANDLER
#include <IKEYHDR.HPP>
#endif
#ifdef INCL_ILISTBOXDRAWITEMEVENT
#include <ILBDIEVT.HPP>
#endif
#ifdef INCL_ILISTBOXDRAWITEMHANDLER
#include <ILBDIHDR.HPP>
#endif
#ifdef INCL_ILISTBOX
#include <ILISTBOX.HPP>
#endif
#ifdef INCL_IMULTICELLCANVAS
#include <IMCELCV.HPP>
#endif
#ifdef INCL_IMOUSECLICKEVENT
#include <IMCEVT.HPP>
#endif
#ifdef INCL_IMOUSECLICKHANDLER
#include <IMOUSHDR.HPP>
#endif
#ifdef INCL_IMENU
#include <IMENU.HPP>
#endif
#ifdef INCL_IMENUBAR
#include <IMENUBAR.HPP>
#endif
#ifdef INCL_IMENUEVENT
#include <IMENUEVT.HPP>
#endif
#ifdef INCL_IMENUHANDLER
#include <IMENUHDR.HPP>
#endif
#ifdef INCL_IMULTILINEEDIT
#include <IMLE.HPP>
#endif
#ifdef INCL_IMENUDRAWITEMEVENT
#include <IMNDIEVT.HPP>
#endif
#ifdef INCL_IMENUDRAWITEMHANDLER
#include <IMNDIHDR.HPP>
#endif
#ifdef INCL_IMENUITEM
#include <IMNITEM.HPP>
#endif
#ifdef INCL_IMESSAGEBOX
#include <IMSGBOX.HPP>
#endif
#ifdef INCL_IMESSAGETEXT
#include <IMSGTEXT.HPP>
#endif
#ifdef INCL_INOTEBOOKDRAWITEMEVENT
#include <INBDIEVT.HPP>
#endif
#ifdef INCL_IPAGEHANDLE
#include <INOTEBK.HPP>
#endif
#ifdef INCL_INOTEBOOK
#include <INOTEBK.HPP>
#endif
#ifdef INCL_PAGESETTINGS
#include <INOTEBK.HPP>
#endif
#ifdef INCL_IOBJECTWINDOW
#include <IOBJWIN.HPP>
#endif
#ifdef INCL_IOUTLINEBOX
#include <IOUTLBOX.HPP>
#endif
#ifdef INCL_IPAGEEVENT
#include <IPAGEEVT.HPP>
#endif
#ifdef INCL_IPAGEREMOVEEVENT
#include <IPAGEEVT.HPP>
#endif
#ifdef INCL_IPAGEHELPEVENT
#include <IPAGEEVT.HPP>
#endif
#ifdef INCL_IPAGESELECTEVENT
#include <IPAGEEVT.HPP>
#endif
#ifdef INCL_IPAGEHANDLER
#include <IPAGEHDR.HPP>
#endif
#ifdef INCL_IPAINTEVENT
#include <IPAINEVT.HPP>
#endif
#ifdef INCL_IPAINTHANDLER
#include <IPAINHDR.HPP>
#endif
#ifdef INCL_IPAIR
#include <IPOINT.HPP>
#endif
#ifdef INCL_IPOINT
#include <IPOINT.HPP>
#endif
#ifdef INCL_ISIZE
#include <IPOINT.HPP>
#endif
#ifdef INCL_IRANGE
#include <IPOINT.HPP>
#endif
#ifdef INCL_IPOPUPMENU
#include <IPOPMENU.HPP>
#endif
#ifdef INCL_IPROCEDUREADDRESS
#include <IPROCADR.HPP>
#endif
#ifdef INCL_IPROFILE
#include <IPROFILE.HPP>
#endif
#ifdef INCL_IPUSHBUTTON
#include <IPUSHBUT.HPP>
#endif
#ifdef INCL_IRADIOBUTTON
#include <IRADIOBT.HPP>
#endif
#ifdef INCL_IRECTANGLE
#include <IRECT.HPP>
#endif
#ifdef INCL_IREFCOUNTED
#include <IREFCNT.HPP>
#endif
#ifdef INCL_IREFERENCE
#include <IREFCNT.HPP>
#endif
#ifdef INCL_IRESOURCELIBRARY
#include <IRESLIB.HPP>
#endif
#ifdef INCL_IDYNAMICLINKLIBRARY
#include <IRESLIB.HPP>
#endif
#ifdef INCL_IRESOURCEID
#include <IRESLIB.HPP>
#endif
#ifdef INCL_IRESOURCE
#include <IRESLOCK.HPP>
#endif
#ifdef INCL_IPRIVATERESOURCE
#include <IRESLOCK.HPP>
#endif
#ifdef INCL_ISHAREDRESOURCE
#include <IRESLOCK.HPP>
#endif
#ifdef INCL_IRESOURCELOCK
#include <IRESLOCK.HPP>
#endif
#ifdef INCL_ISCROLLEVENT
#include <ISCRLEVT.HPP>
#endif
#ifdef INCL_ISCROLLHANDLER
#include <ISCRLHDR.HPP>
#endif
#ifdef INCL_ISCROLLBAR
#include <ISCROLL.HPP>
#endif
#ifdef INCL_ISELECTHANDLER
#include <ISELHDR.HPP>
#endif
#ifdef INCL_ISETTINGBUTTON
#include <ISETBUT.HPP>
#endif
#ifdef INCL_ISETCANVAS
#include <ISETCV.HPP>
#endif
#ifdef INCL_IRESIZEEVENT
#include <ISIZEEVT.HPP>
#endif
#ifdef INCL_IRESIZEHANDLER
#include <ISIZEHDR.HPP>
#endif
#ifdef INCL_ISHOWLISTHANDLER
#include <ISLHDR.HPP>
#endif
#ifdef INCL_IPROGRESSINDICATOR
#include <ISLIDER.HPP>
#endif
#ifdef INCL_ISLIDER
#include <ISLIDER.HPP>
#endif
#ifdef INCL_ISLIDERDRAWHANDLER
#include <ISLIDHDR.HPP>
#endif
#ifdef INCL_ISPINBUTTON
#include <ISPINBT.HPP>
#endif
#ifdef INCL_ISPINHANDLER
#include <ISPINHDR.HPP>
#endif
#ifdef INCL_ISPLITCANVAS
#include <ISPLITCV.HPP>
#endif
#ifdef INCL_ISTATICTEXT
#include <ISTATTXT.HPP>
#endif
#ifdef INCL_ISTRINGENUM
#include <ISTRENUM.HPP>
#endif
#ifdef INCL_ISTRING
#include <ISTRING.HPP>
#endif
#ifdef INCL_ISTRINGTEST
#include <ISTRTEST.HPP>
#endif
#ifdef INCL_ISUBMENU
#include <ISUBMENU.HPP>
#endif
#ifdef INCL_ISWP
#include <ISWP.HPP>
#endif
#ifdef INCL_ISWPARRAY
#include <ISWP.HPP>
#endif
#ifdef INCL_ISYSTEMMENU
#include <ISYSMENU.HPP>
#endif
#ifdef INCL_ITEXTCONTROL
#include <ITEXTCTL.HPP>
#endif
#ifdef INCL_ITHREAD
#include <ITHREAD.HPP>
#endif
#ifdef INCL_ICURRENTTHREAD
#include <ITHREAD.HPP>
#endif
#ifdef INCL_ITIME
#include <ITIME.HPP>
#endif
#ifdef INCL_ITITLE
#include <ITITLE.HPP>
#endif
#ifdef INCL_ITRACE
#include <ITRACE.HPP>
#endif
#ifdef INCL_IVBASE
#include <IVBASE.HPP>
#endif
#ifdef INCL_IVIEWPORT
#include <IVPORT.HPP>
#endif
#ifdef INCL_IWINDOW
#include <IWINDOW.HPP>
#endif
